site_name: CiscoLive EMEA 2023 --- LTRCLD-2557
site_description: Explore Simplicity of Public Cloud Network Configuration with Cloud Network Controller (formerly cAPIC) and Nexus Dashboard Orchestrator (NDO)
site_author: Marcin Duma & Karol Okraska

nav:
  - Home: index.md #opis laba z HLD - obrazkiem
  - Lab Access:
    - Accessing the Lab Environment: LAB_access.md
  - INFRA Configuration: 
    - Sites onboarding: infra-config.md
    - Multisite configuration: infra-config-msite.md
  - Tenant configuration:
    - NDO Tenant configuration: ndo-tenant.md
    - AWS Trust: aws-trust.md
  - Use-cases:
    - Stretched VRF: terraform-installation.md
    - Internet Gateway: terraform-installation.md
    - Inter-Tenant routing: terraform-installation.md
  - Appendixes:
    - ACI to Public Cloud Object mapping: object-map.md
    - Resources: resources.md
    - PRINT version: print_page/
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
plugins:
  - search
  - print-site:
      add_cover_page: true
      cover_page_template: "docs/assets/templates/custom_cover_page.tpl"
      add_print_site_banner: true
      print_site_banner_template: "docs/assets/templates/custom_banner.tpl"
      exclude:
        - guacamole.md
        - resources.md
        - URL-restAPI.md