site_name: CiscoLive EMEA 2023 --- LTRCLD-2557
site_description: Explore Simplicity of Public Cloud Network Configuration with Cloud Network Controller (formerly cAPIC) and Nexus Dashboard Orchestrator (NDO)
site_author: Marcin Duma & Karol Okraska

nav:
  - Home: index.md #opis laba z HLD - obrazkiem
  - Lab Access:
    - Accessing the Lab Environment: LAB_access.md
  - INFRA Configuration: 
    - Sites onboarding: infra-config.md
    - Multisite configuration: infra-config-msite.md
  - Tenant configuration:
    - NDO Tenant configuration: ndo-tenant.md
    - AWS Trust: aws-trust.md
  - Use-cases:
    - Use-case 01 - Stretched VRF: use-case1.md
    - Use-case 02 - Internet Gateway: use-case2.md
    - Use-case 03 - Inter-Tenant routing: use-case3.md
  - Appendixes:
    - Lab details:
      - POD-01: pod1.md
      - POD-02: pod2.md
      - POD-03: pod3.md
      - POD-04: pod4.md
      - POD-05: pod5.md
      - POD-06: pod6.md
      - POD-07: pod7.md
      - POD-08: pod8.md
      - POD-09: pod9.md
      - POD-10: pod10.md
    - ACI to Public Cloud Object mapping: object-map.md
    - Resources: resources.md
    - PRINT version: print_page/
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - tables
plugins:
  - search
  - print-site:
      add_cover_page: true
      cover_page_template: "docs/assets/templates/custom_cover_page.tpl"
      add_print_site_banner: true
      print_site_banner_template: "docs/assets/templates/custom_banner.tpl"
      exclude:
        - guacamole.md
        - resources.md
        - URL-restAPI.md
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
      - custom-skip-class-name
      auto_caption: false
      caption_position: bottom